config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/controllers/home_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class HomeController < ApplicationController
  before_action :require_user, except: [:toggle, :timezone]
  before_action :set_current_tab, only: :index

  #----------------------------------------------------------------------------
  def index
    @activities = get_activities
    @my_tasks = Task.visible_on_dashboard(current_user).includes(:user, :asset).by_due_at
    @my_opportunities = Opportunity.visible_on_dashboard(current_user).includes(:account, :user, :tags).by_closes_on.by_amount
    @my_accounts = Account.visible_on_dashboard(current_user).includes(:user, :tags).by_name
    respond_with(@activities)
  end

  # GET /home/options                                                      AJAX
  #----------------------------------------------------------------------------
  def options
    unless params[:cancel].true?
      @asset = current_user.pref[:activity_asset] || "all"
      @action = current_user.pref[:activity_event] || "all_events"
      @user = current_user.pref[:activity_user] || "all_users"
      @duration = current_user.pref[:activity_duration] || "two_days"
      @all_users = User.order("first_name, last_name")
    end
  end

  # GET /home/redraw                                                       AJAX
  #----------------------------------------------------------------------------
  def redraw
    current_user.pref[:activity_asset] = params[:asset] if params[:asset]
    current_user.pref[:activity_event] = params[:event] if params[:event]
    current_user.pref[:activity_user] = params[:user] if params[:user]
    current_user.pref[:activity_duration] = params[:duration] if params[:duration]
    @activities = get_activities

    respond_with(@activities) do |format|
      format.js { render :index }
    end
  end

  # GET /home/toggle                                                       AJAX
  #----------------------------------------------------------------------------
  def toggle
    if session[params[:id].to_sym]
      session.delete(params[:id].to_sym)
    else
      session[params[:id].to_sym] = true
    end
    render nothing: true
  end

  # GET /home/timeline                                                     AJAX
  #----------------------------------------------------------------------------
  def timeline
    state = params[:state].to_s
    if %w(Collapsed Expanded).include?(state)
      if (model_type = params[:type].to_s).present?
        if %w(comment email).include?(model_type)
          model = model_type.camelize.constantize
          item = model.find(params[:id])
          item.update_attribute(:state, state)
        end
      else
        comments, emails = params[:id].split("+")
        Comment.where(id: comments.split(',')).update_all(state: state) unless comments.blank?
        Email.where(id: emails.split(',')).update_all(state: state) unless emails.blank?
      end
    end

    render nothing: true
  end

  # GET /home/timezone                                                     AJAX
  #----------------------------------------------------------------------------
  def timezone
    #
    # (new Date()).getTimezoneOffset() in JavaScript returns (UTC - localtime) in
    # minutes, while ActiveSupport::TimeZone expects (localtime - UTC) in seconds.
    #
    if params[:offset]
      session[:timezone_offset] = params[:offset].to_i * -60
      ActiveSupport::TimeZone[session[:timezone_offset]]
    end
    render nothing: true
  end

  private

  #----------------------------------------------------------------------------
  def get_activities(options = {})
    options[:asset]    ||= activity_asset
    options[:event]    ||= activity_event
    options[:user]     ||= activity_user
    options[:duration] ||= activity_duration
    options[:max]      ||= 500

    Version.includes(user: [:avatar]).latest(options).visible_to(current_user)
  end

  #----------------------------------------------------------------------------
  def activity_asset
    asset = current_user.pref[:activity_asset]
    if asset.nil? || asset == "all"
      nil
    else
      asset.singularize.capitalize
    end
  end

  #----------------------------------------------------------------------------
  def activity_event
    event = current_user.pref[:activity_event]
    if event == "all_events"
      %w(create update destroy)
    else
      event
    end
  end

  #----------------------------------------------------------------------------
  # TODO: this is ugly, ugly code. It's being security patched now but urgently
  # needs refactoring to use user id instead. Permuations based on name or email
  # yield incorrect results.
  def activity_user
    user = current_user.pref[:activity_user]
    if user && user != "all_users"
      user = if user =~ /@/ # email
               User.where(email: user).first
             else # first_name middle_name last_name any_name
               name_query = if user.include?(" ")
                              user.name_permutations.map do |first, last|
                                User.where(first_name: first, last_name: last)
                              end.map(&:to_a).flatten.first
                            else
                              [User.where(first_name: user), User.where(last_name: user)].map(&:to_a).flatten.first
               end
        end
    end
    user.is_a?(User) ? user.id : nil
  end

  #----------------------------------------------------------------------------
  def activity_duration
    duration = current_user.pref[:activity_duration]
    if duration
      words = duration.split("_") # "two_weeks" => 2.weeks
      if %w(one two).include?(words.first) && %w(hour day days week weeks month).include?(words.last)
        %w(zero one two).index(words.first).send(words.last)
      end
    end
  end
end

app/helpers/home_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module HomeHelper
  def sort_by_assets
    Version::ASSETS.map do |asset|
      %[{ name: "#{t(asset.singularize)}", on_select: function() { #{redraw(:asset, [asset, t(asset.singularize).downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_events
    Version::EVENTS.map do |event|
      %[{ name: "#{t(event + '_past_participle')}", on_select: function() { #{redraw(:event, [event, t(event + '_past_participle').downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_duration
    Version::DURATION.map do |duration|
      %[{ name: "#{t(duration)}", on_select: function() { #{redraw(:duration, [duration, t(duration).downcase], url_for(action: :redraw))} } }]
    end
  end

  #----------------------------------------------------------------------------
  def sort_by_users
    users = [["all_users", t(:option_all_users)]] + @all_users.map do |user|
      escaped = sanitize(user.full_name)
      [escaped, escaped]
    end

    users.map do |key, value|
      %[{ name: "#{value}", on_select: function() { #{redraw(:user, [key, (value == t(:option_all_users) ? value.downcase : value)], url_for(action: :redraw))} } }]
    end
  end

  # Activity title for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def activity_title(activity)
    user    = activity.user.try(:full_name) || ''
    action  = t('action_' + activity.event)
    type    = t('subject_' + activity.item_type.downcase)
    subject = if item = activity.item
                if item.respond_to?(:full_name)
                  item.full_name
                elsif item.respond_to?(:name)
                  item.name
                end
    end
    t(:activity_text, user: user, action: action, type: type, subject: subject,
                      default: "#{user} #{action} #{type} #{subject}")
  end

  # Displays 'not showing' message for a given count, entity and limit
  def show_hidden_entities_message(count, entity, limit = 10)
    if count > limit
      hidden_count = count - 10
      entity_string = I18n.t("#{hidden_count == 1 ? entity : entity.pluralize}_small")
      content_tag(:p) do
        t(:not_showing_hidden_entities, entity: entity_string, count: hidden_count)
      end
    end
  end
end

app/views/home/_account.html.erb
<% amount = account.opportunities.not_lost.map(&:weighted_amount).sum %>
<li class="highlight account" id="<%= account.id %>">
  <% if account.category %>
    <div class="strip <%= account.category %>">
      <%= t(account.category) %>
    </div>
  <% else %>
    <div class="strip" style="color: gray;">
      <%= t :other %>
    </div>
  <% end %>

  <div class="indent">
    <%= link_to(h(account.name), account) %>
    &ndash;
    <tt>
      <%= account.location << ", " unless account.location.blank? %>

      <% user_name = account.user.try(:full_name) %>

      <% if user_name %>
        <%= t(:added_by, :time_ago => timeago(account.created_at), :user => h(user_name)).html_safe %>
      <% else %>
        <%= t(:added_ago, :value => timeago(account.created_at)).html_safe %>
      <% end %>
    </tt>

    <% unless current_user.preference[:accounts_index_view] == "accounts_index_brief" %>
      <dt>
        <%= link_to(account.website, account.website.to_url) << " | " if account.website.present? %>

        <%= link_to_email(account.email) << " | " if account.email.present? %>

        <%= t(:phone_small) << ": " << (account.toll_free_phone || account.phone) << " | " if account.toll_free_phone? || account.phone? %>

         <%= t('pluralize.contact', account.contacts.count) << " | " %>

        <%= t('pluralize.opportunity', account.opportunities.count) %>
      </dt>

      <% if account.tags.present? %>
        <dt>
          <div class="tags">
            <%= tags_for_dashboard(account) %>
          </div>
        </dt>
      <% end %>

      <%= hook(:account_bottom, self, :account => account) %>
    <% end %>
  </div>
</li>

app/views/home/_activity.html.erb
<% user = link_to(activity.user.full_name, user_path(activity.user)) if activity.user %>

<% subject = if (item = activity.related || activity.item) %>
  <% if item.respond_to?(:full_name) %>
    <% link_to item.full_name, polymorphic_url(item) %>

  <% elsif [Account, Campaign, Contact, Lead, Opportunity].include?(item.class) %>
    <% link_to item.name, polymorphic_url(item) %>
  <% elsif item.respond_to?(:name) %>
    <% content_tag :span, item.name, :style => "color:black;" %>
    <%# Individual tasks have no landing pages where we could link to. %>
  <% end %>
<% end %>

<% known_event = t('action_' + activity.event, :default => 0) != 0 %>

<% if (user.present? && subject.present?) || !known_event %>
  <li class="activity" id="<%=activity.id %>">
    <div class="tools">
      <small>
        <%= l(activity.created_at, :format => :short) %>
      </small>
    </div>

    <tt>
      <% if known_event %>
        <% action = t('action_' + activity.event) %>
        <% type = t('subject_' + activity.item_type.downcase) %>
        <%= link_to avatar_for(activity.user, :size => :thumb), user_path(activity.user) %>
        <%= t("activity_text", :user => h(user), :action => h(action), :type => h(type), :subject => h(subject), :default => "#{h user} #{h action} #{h type} #{h subject}").html_safe %>
        <%# locales optionally can change the word order for activities using 'activity_text' %>

        <% if ((item = activity.item).class == Comment) and Setting.comments_visible_on_dashboard %>
          <%= t('action_create_comment', :comment => truncate(h(item.comment), :length => 90)).html_safe %>
        <% end %>
      <% else %>
        <% type = t(activity.item_type.downcase) %>

        <% if item.respond_to? :email %>
          <%= avatar_for(item, :size => :thumb) %>
        <% end %>

        <%= type %>
        <%= subject %>
        <%= ":" %>
        <%= auto_link(t(activity.event)) %>
      <% end %>
    </tt>
  </li>
<% end %>

app/views/home/_assets_menu.html.erb
new crm.Menu({
  trigger   : "#asset",
  fade      : 500,
  appear    : 500,
  menu_items: [ #{sort_by_assets.join(",")} ]
});

app/views/home/_duration_menu.html.erb
new crm.Menu({
  trigger   : "#duration",
  fade      : 500,
  appear    : 500,
  width     : 165,
  menu_items: [ #{sort_by_duration.join(",")} ]
});

app/views/home/_events_menu.html.erb
new crm.Menu({
  trigger   : "#event",
  fade      : 500,
  appear    : 500,
  menu_items: [ #{sort_by_events.join(",")} ]
});

app/views/home/_events_menu.html.haml
:plain
  new crm.Menu({
    trigger   : "#event",
    fade      : 500,
    appear    : 500,
    menu_items: [ #{sort_by_events.join(",")} ]
  });

app/views/home/_opportunity.html.erb
<li class="highlight opportunity">
  <% if opportunity.stage %>
    <div class="strip <%= opportunity.stage %>">
      <%= t(opportunity.stage) %>
    </div>
  <% else %>
    <div class="strip white">
      <%= t :other %>
    </div>
  <% end %>

  <div class="indent">
    <%= link_to(h(opportunity.name), opportunity) %>

    <% if opportunity.account %>
      <%= t :from %>
      <%= link_to(h(opportunity.account.name), account_path(opportunity.account)) %>
    <% end %>

    <tt>
      &ndash;
      <% user_name = opportunity.user.try(:full_name) %>
      <% if user_name %>
        <%= t(:added_by, :time_ago => timeago(opportunity.created_at), :user => h(user_name)).html_safe %>
      <% else %>
        <%= t(:added_ago, :value => timeago(opportunity.created_at)).html_safe %>
      <% end %>
    </tt>

    <% unless current_user.preference[:opportunities_index_view] == "opportunities_index_brief" %>
      <dt>
        <b>
          <%= number_to_currency(opportunity.weighted_amount, :precision => 0) + " | " %>
        </b>

        <% won_or_lost = %w(won lost).include?(opportunity.stage) %>

        <% unless won_or_lost %>
          <%= t(:probability_number, (opportunity.probability || 0).to_s + '%') + " | " %>
        <% end %>

        <% if opportunity.closes_on %>
          <% if won_or_lost %>
            <% if opportunity.closes_on >= Date.today %>
              <%= t(:closing_date, l(opportunity.closes_on, :format => :mmddyy)) %>
            <% else %>
              <%= t(:closed_ago_on, :time_ago => distance_of_time_in_words(opportunity.closes_on, Date.today), :date => l(opportunity.closes_on, :format => :mmddyy)) %>
            <% end %>
          <% elsif opportunity.closes_on > Date.today %>
            <%= t(:expected_to_close,  :time => distance_of_time_in_words(Date.today, opportunity.closes_on), :date => l(opportunity.closes_on, :format => :mmddyy)) %>
          <% elsif opportunity.closes_on == Date.today %>
            <span class="warn">
              <%= t(:closes_today) %>
            </span>
          <% else %>
            <span class="warn">
              <%= t(:past_due, distance_of_time_in_words(opportunity.closes_on, Date.today)) %>
            </span>
          <% end %>
        <% else %>
          <%= t(:no_closing_date) %>
        <% end %>
      </dt>

      <% if opportunity.tags.present? %>
        <dt>
          <div class="tags">
            <%= tags_for_dashboard(opportunity) %>
          </div>
        </dt>
      <% end %>

      <%= hook(:opportunity_bottom, self, :opportunity => opportunity) %>
    <% end %>
  </div>
</li>

app/views/home/_options.html.erb
<p>
  <%= link_to_close url_for(:action => "options") %>
  <%= hidden_field_tag "account[user_id]", current_user.id %>
  <%# activity_options: Show %{models} %{action_type} performed by %{user} in the past %{period} %>
  <%= t(:activity_options, :models => link_to(t(h(@asset)).singularize.downcase, "#", :id => :asset), :action_type => link_to(t(h(@action) + "_past_participle").downcase, "#", :id => :event), :user => link_to(t(h(@user)), "#", :id => :user), :period => link_to(t(h(@duration)).downcase, "#", :id => :duration)).html_safe %>
</p>

<script>
  <%= render "assets_menu" %> 
  <%= render "events_menu" %>
  <%= render "users_menu" %>
  <%= render "duration_menu" %>
</script>

app/views/home/_task.html.erb
<li class="highlight task" id="<%= task.id %>">
  <% unless task.category.blank? %>
    <div class="strip <%= task.category %>">
      <%= t(task.category) %>
    </div>
  <% else %>
    <div class="strip white">
      <%= t :other %>
    </div>
  <% end %>
  
  <div class="indent">
    <label id="<%= dom_id(task, :name) %>">
      <% if task.user.id != current_user.id %>
        <%= t(:task_from, link_to(h(task.user.full_name), user_path(task.user))).html_safe << ':' %>
      <% end %>

      <%= link_to(task.name, tasks_path) %>

      <% if task.asset_id? %>
        <%= t :related %> <%= link_to(task.asset.name, polymorphic_url(task.asset)) %>
      <% end %>
      &ndash;
    </label>

    <tt>
      <% if task.bucket == "due_asap" %>
        <span class="urgent">
          <%= t(:task_due_now) %>
        </span>
      <% elsif task.bucket == "due_later" %>
        <%= t(:task_due_later) %>
      <% else %>
        <% if task.due_at.nil? %>
          <%= t(:task_due_later) %>
        <% elsif task.at_specific_time? %>
          <% if task.due_at < Time.now %>
            <span class="warn">
              <%= distance_of_time_in_words(task.due_at, Time.now) %>

              <%= t(:task_overdue) %>

              <%= l(task.due_at.localtime, :format => :mmddhhss) %>
            </span>
          <% else %>
            <%= t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at)) %>

            <%= '(' << l(task.due_at.localtime, :format => :mmddhhss) << ')' %>
          <% end %>
        <% else %>
          <% if task.due_at < Date.today %>
            <span class="warn">
              <%= distance_of_time_in_words(task.due_at, Time.now) %>

              <%= t(:task_overdue) %>

              <%= l(task.due_at.localtime.to_date, :format => :mmdd) %>
            </span>
          <% elsif task.due_at > Date.today %>
            <%= t(:task_due_in, distance_of_time_in_words(Time.now, task.due_at.localtime.end_of_day)) %>

            <%= ' (' << l(task.due_at.localtime.to_date, :format => :mmdd) << ')' %>
          <% else %>
            <span class="cool">
              <%= t(:task_due_today) %>
            </span>
          <% end %>
        <% end %>
      <% end %>
    </tt>

    <% unless task.background_info.blank? %>
      <div>
        <dt>
          <%= auto_link(simple_format task.background_info) %>
        </dt>
      </div>
    <% end %>
  </div>
</li>

app/views/home/_users_menu.html.erb
new crm.Menu({
  trigger   : "#user",
  fade      : 500,
  appear    : 500,
  width     : 180,
  menu_items: [ #{sort_by_users.join(',')} ]
});

app/views/home/index.html.erb
<%= styles_for :task, :opportunity, :account %>

<div class="title">
  <span id="title">
    <%= t :my_tasks %>
  </span>
</div>

<ul class="list" id="tasks">
  <% unless @my_tasks.empty? %>
    <%= render :partial => "home/task", :collection => @my_tasks.limit(10) %>
    <%= show_hidden_entities_message(@my_tasks.count, 'task', 10) %>
  <% else %>
    <%= t :no_task_records %>
  <% end %>
</ul>

<div class="title">
  <span id="title">
    <%= t :my_opportunities %>
  </span>
</div>

<ul class="list" id="opportunities">
  <% unless @my_opportunities.empty? %>
    <%= render :partial => "home/opportunity", :collection => @my_opportunities.limit(10) %>
    <%= show_hidden_entities_message(@my_opportunities.count, 'opportunity', 10) %>
  <% else %>
    <%= t :no_opportunity_records %>
  <% end %>
</ul>

<div class="title">
  <span id="title">
    <%= t :my_accounts %>
  </span>
</div>

<ul class="list" id="accounts">
  <% unless @my_accounts.empty? %>
    <%= render :partial => "home/account", :collection => @my_accounts.limit(10) %>
    <%= show_hidden_entities_message(@my_accounts.count, 'account', 10) %>
  <% else %>
    <%= t :no_account_records %>
  <% end %>
</ul>

<div class="title_tools">
  <%= link_to_inline(:options, url_for(:action => :options), :text => t(:options)) %>
</div>

<div class="title">
  <span id="title">
    <%= t :recent_activity %>
  </span>

  <%= image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;") %>
</div>

<div class="remote" id="options" hidden></div>

<ul class="list" id="activities">
  <% unless @activities.empty? %>
    <%= render :partial => "activity", :collection => @activities %>
  <% else %>
    <%= t :no_activity_records %>
  <% end %>
</ul>


<div id="export">
  <%= render "shared/export" %>
</div>

app/views/home/index.js.erb
<% unless @activities.blank? %>
  $('#activities').html('<%= j render(:partial => "activity", :collection => @activities) %>');
<% else %>
  $('#activities').html('<%= j t(:no_activity_records) %>');
<% end %>

<%# $('#paginate').html('#{ j render(:partial => "shared/paginate") }'); %>
$('#export').html('<%= j render(:partial => "shared/export") %>');

app/views/home/options.js.erb
crm.flip_form('options');

<% unless params[:cancel].true? %>
  $('#options').html('<%= j render(:partial => "options") %>');
  crm.set_title('title', '<%= j t(:recent_activity_options) %>');
<% else %>
  crm.set_title('title', '<%= j t(:recent_activity) %>');
<% end %>