config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/models/users/group.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :permissions

  validates :name, presence: true, uniqueness: true

  ActiveSupport.run_load_hooks(:fat_free_crm_group, self)
end

app/controllers/admin/groups_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class Admin::GroupsController < Admin::ApplicationController
  before_action "set_current_tab('admin/groups')", only: [:index, :show]

  load_resource

  # GET /groups
  #----------------------------------------------------------------------------
  def index
    @groups = @groups.unscoped.paginate(page: params[:page])
  end

  # GET /groups/1
  #----------------------------------------------------------------------------
  def show
    respond_with(@group)
  end

  # GET /groups/new
  #----------------------------------------------------------------------------
  def new
    respond_with(@group)
  end

  # GET /groups/1/edit
  #----------------------------------------------------------------------------
  def edit
    respond_with(@group)
  end

  # POST /groups
  #----------------------------------------------------------------------------
  def create
    @group.attributes = group_params
    @group.save

    respond_with(@group)
  end

  # PUT /groups/1
  #----------------------------------------------------------------------------
  def update
    @group.update_attributes(group_params)

    respond_with(@group)
  end

  # DELETE /groups/1
  #----------------------------------------------------------------------------
  def destroy
    @group.destroy

    respond_with(@group)
  end

  protected

  def group_params
    params[:group].permit!
  end
end

app/helpers/groups_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module GroupsHelper
end

app/views/admin/backup_originals/groups/_edit.html.haml
.remote
  = form_for([:admin, @group], :html => one_submit_only.merge({:autocomplete => 'off'}), :remote => true) do |f|
    = link_to_close edit_admin_group_path(@group)

    = f.error_messages :object_name => t('group')

    = render "admin/groups/form", :f => f, :edit => true

    .buttonbar
      = f.submit t(:save_group)
      #{t :or}
      = link_to_cancel edit_admin_group_path(@group)

app/views/admin/backup_originals/groups/_form.html.haml
.section
  %table
    %tr
      %td
        .label.top.req #{t :name}:
        = f.text_field :name
    %tr
      %td
        .label.top.req #{t :users}:
        %br
        = f.select :user_ids, User.all.map {|u| [u.full_name, u.id]}, {}, :multiple => true, :class => 'select2'

app/views/admin/backup_originals/groups/_group.html.haml
%li.highlight[group]

  %ul.tools
    %li= link_to_edit [:admin, group]
    - count = Permission.where(:group_id => group.id).count
    - confirm = (count.zero? ? nil : "#{t(:confirm_group_delete, count)}")
    %li= link_to_delete [:admin, group], :confirm => confirm

  %span
    =link_to(group.name, {:action => :edit, :id => group.id}, {:remote  => true,
          :onclick => "this.href = this.href.split('?')[0] + '?previous='+crm.find_form('edit_group');"})
  %tt
    - if (users = group.users).present?
      == #{t('group_members')}:
      - users.map do |user|
        = link_to( h(user.full_name), user )

app/views/admin/backup_originals/groups/_new.html.haml
= form_for([:admin, @group], :html => one_submit_only.merge({:autocomplete => 'off'}), :remote => true) do |f|
  = link_to_close new_admin_group_path

  = f.error_messages :object_name => t('group')

  = render "admin/groups/form", :f => f

  .buttonbar
    = f.submit t(:create_group)
    #{t :or}
    = link_to_cancel new_admin_group_path

app/views/admin/backup_originals/groups/create.js.haml
- if @group.valid?
  $('#create_group_arrow').html(crm.COLLAPSED);
  $('#create_group_title').html('#{ j t(:groups) }');
  $('#create_group').slideUp(250);
  $('#groups').prepend('#{ j (render :partial => "group", :collection => [ @group ]) }');
  $('##{dom_id(@group)}').effect("highlight", { duration:1500 });
- else
  $('#create_group').html('#{ j render(:partial => "new") }');
  $('#create_group').effect("shake", { duration:250, distance: 6 });
  $('#group_name').focus();

app/views/admin/backup_originals/groups/destroy.js.haml
- id = dom_id(@group)
- if @group.destroyed?
  $('##{id}').css('background-color', '#ffe4e1').slideUp(250);
- else
  crm.flick("#{dom_id(@group, :confirm)}, 'remove')");
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('#flash').html('#{ j flash[:warning] }');
  crm.flash('warning');
  - flash[:warning] = nil

app/views/admin/backup_originals/groups/edit.js.haml
- id = dom_id(@group)

- if params[:cancel].true?     # <----------------- Hide [Edit Group]
  $('##{id}').replaceWith('#{ j (render(:partial => "group", :collection => [ @group ])) }');

- else # <----------------------------------------  Show [Edit Group] form.

  -# Disable onMouseOver for the list item.
  crm.highlight_off('#{id}');
  -# Hide [Create Group] form if any.
  crm.hide_form('create_group');
  -# Show [Edit Group] form.
  $('##{id}').html('#{ j render(:partial => "edit") }');
  $('#group_name').focus();

app/views/admin/backup_originals/groups/index.html.haml
= styles_for :group

.title_tools
  = link_to_inline(:create_group, new_admin_group_path, :text => t(:create_group))

.title
  %span#create_group_title #{t :groups}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")

.remote#create_group{ hidden }

%ul.list#groups
  - if @groups.any?
    = render :partial => "group", :collection => @groups
  - else
    = render "shared/empty"

#paginate= render "shared/paginate"

app/views/admin/backup_originals/groups/index.js.haml
$('#groups').html('#{ j render(:partial => "admin/groups/group", :collection => @groups) }');
$('#paginate').html('#{ j render(:partial => "shared/paginate") }')

app/views/admin/backup_originals/groups/new.js.haml
crm.flip_form('create_group');

- unless params[:cancel].true?
  $('#create_group').html('#{ j render(:partial => "new") }');
  $('#empty').html('');
  crm.set_title('create_group', '#{t(:create_group)}');

- else
  crm.set_title('create_group', '#{t(:groups)}');

app/views/admin/backup_originals/groups/show.html.haml
.title= h(@group.name)

.members
  - @group.users.each do |user|
    .user
      = h(user.name)

%p
  = link_to t(:edit), edit_admin_group_path(@group)
  |
  = link_to t(:back), admin_groups_path

app/views/admin/backup_originals/groups/update.js.haml
- id = dom_id(@group)

- if @group.errors.empty?
  $('##{id}').replaceWith('#{ j render(:partial => "group", :collection => [ @group ]) }')
  $('##{id}').effect("highlight", { duration:1000 });
- else
  $('##{id}').html('#{j render(:partial => "edit") }')
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('#group_name').focus()