config/routes.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root to: 'home#index'

  get 'activities' => 'home#index'
  get 'admin'      => 'admin/users#index',       :as => :admin
  get 'login'      => 'authentications#new',     :as => :login
  delete 'logout'  => 'authentications#destroy', :as => :logout
  get 'profile'    => 'users#show',              :as => :profile
  get 'signup'     => 'users#new',               :as => :signup

  get '/home/options',  as: :options
  get '/home/toggle',   as: :toggle
  match '/home/timeline', as: :timeline, via: [:get, :put, :post]
  match '/home/timezone', as: :timezone, via: [:get, :put, :post]
  post '/home/redraw',   as: :redraw

  resource :authentication, except: [:index, :edit]
  resources :comments,       except: [:new, :show]
  resources :emails,         only: [:destroy]
  resources :passwords,      only: [:new, :create, :edit, :update]

  resources :accounts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
      get :opportunities
    end
  end

  resources :campaigns, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :leads
      get :opportunities
    end
  end

  resources :contacts, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :opportunities
    end
  end

  resources :leads, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
      get :autocomplete_account_name
    end
    member do
      get :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put :attach
      match :promote, via: [:patch, :put]
      put :reject
    end
  end

  resources :opportunities, id: /\d+/ do
    collection do
      get :advanced_search
      post :filter
      get :options
      get :field_group
      match :auto_complete, via: [:get, :post]
      get :redraw
      get :versions
    end
    member do
      put :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get :contacts
    end
  end

  resources :tasks, id: /\d+/ do
    collection do
      post :filter
      match :auto_complete, via: [:get, :post]
    end
    member do
      put :complete
      put :uncomplete
    end
  end

  resources :users, id: /\d+/, except: [:index, :destroy] do
    member do
      get :avatar
      get :password
      match :upload_avatar, via: [:put, :patch]
      patch :change_password
      post :redraw
    end
    collection do
      match :auto_complete, via: [:get, :post]
      get :opportunities_overview
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete, via: [:get, :post]
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, except: [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete, via: [:get, :post]
        get :options
        get :redraw
        post :sort
        get :subform
      end
    end

    resources :tags, except: [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, as: :custom_fields
    resources :fields, as: :core_fields

    resources :settings, only: :index
    resources :plugins,  only: :index
  end
end

app/models/users/group.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :permissions

  validates :name, presence: true, uniqueness: true

  ActiveSupport.run_load_hooks(:fat_free_crm_group, self)
end

app/controllers/admin/users_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class Admin::UsersController < Admin::ApplicationController
  before_action "set_current_tab('admin/users')", only: [:index, :show]

  load_resource except: [:create]

  # GET /admin/users
  # GET /admin/users.xml                                                   HTML
  #----------------------------------------------------------------------------
  def index
    @users = get_users(page: params[:page])
    respond_with(@users)
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  #----------------------------------------------------------------------------
  def show
    respond_with(@user)
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml                                               AJAX
  #----------------------------------------------------------------------------
  def new
    respond_with(@user)
  end

  # GET /admin/users/1/edit                                                AJAX
  #----------------------------------------------------------------------------
  def edit
    if params[:previous].to_s =~ /(\d+)\z/
      @previous = User.find_by_id(Regexp.last_match[1]) || Regexp.last_match[1].to_i
    end

    respond_with(@user)
  end

  # POST /admin/users
  # POST /admin/users.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def create
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    @user = User.new(user_params)
    @user.save_without_session_maintenance

    respond_with(@user)
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml                                                 AJAX
  #----------------------------------------------------------------------------
  def update
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    @user = User.find(params[:id])
    @user.attributes = user_params
    @user.save_without_session_maintenance

    respond_with(@user)
  end

  # GET /admin/users/1/confirm                                             AJAX
  #----------------------------------------------------------------------------
  def confirm
    respond_with(@user)
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml                                              AJAX
  #----------------------------------------------------------------------------
  def destroy
    flash[:warning] = t(:msg_cant_delete_user, @user.full_name) unless @user.destroy

    respond_with(@user)
  end

  # POST /users/auto_complete/query                                        AJAX
  #----------------------------------------------------------------------------
  # Handled by Admin::ApplicationController :auto_complete

  # PUT /admin/users/1/suspend
  # PUT /admin/users/1/suspend.xml                                         AJAX
  #----------------------------------------------------------------------------
  def suspend
    @user.update_attribute(:suspended_at, Time.now) if @user != current_user

    respond_with(@user)
  end

  # PUT /admin/users/1/reactivate
  # PUT /admin/users/1/reactivate.xml                                      AJAX
  #----------------------------------------------------------------------------
  def reactivate
    @user.update_attribute(:suspended_at, nil)

    respond_with(@user)
  end

  protected

  def user_params
    params[:user].permit(
      :admin,
      :username,
      :email,
      :first_name,
      :last_name,
      :title,
      :company,
      :alt_email,
      :phone,
      :mobile,
      :aim,
      :yahoo,
      :google,
      :skype,
      :password,
      :password_confirmation,
      group_ids: []
    )
  end

  private

  #----------------------------------------------------------------------------
  def get_users(options = {})
    self.current_page  = options[:page] if options[:page]
    self.current_query = params[:query] if params[:query]

    @search = klass.search(params[:q])
    @search.build_grouping unless @search.groupings.any?

    wants = request.format
    scope = User.by_id
    scope = scope.merge(@search.result)
    scope = scope.text_search(current_query)      if current_query.present?
    scope = scope.paginate(page: current_page) if wants.html? || wants.js? || wants.xml?
    scope
  end
end

app/controllers/users_controller.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
class UsersController < ApplicationController
  before_action :set_current_tab, only: [:show, :opportunities_overview] # Don't hightlight any tabs.

  check_authorization
  load_and_authorize_resource # handles all security

  respond_to :html, only: [:show, :new]

  # GET /users/1
  # GET /users/1.js
  #----------------------------------------------------------------------------
  def show
    @user = current_user if params[:id].nil?
    respond_with(@user)
  end

  # GET /users/new
  # GET /users/new.js
  #----------------------------------------------------------------------------
  def new
    respond_with(@user)
  end

  # POST /users
  # POST /users.js
  #----------------------------------------------------------------------------
  def create
    if @user.save
      if Setting.user_signup == :needs_approval
        flash[:notice] = t(:msg_account_created)
        redirect_to login_url
      else
        flash[:notice] = t(:msg_successful_signup)
        redirect_back_or_default profile_url
      end
    else
      render :new
    end
  end

  # GET /users/1/edit.js
  #----------------------------------------------------------------------------
  def edit
    respond_with(@user)
  end

  # PUT /users/1
  # PUT /users/1.js
  #----------------------------------------------------------------------------
  def update
    @user.update_attributes(user_params)
    respond_with(@user)
  end

  # GET /users/1/avatar
  # GET /users/1/avatar.js
  #----------------------------------------------------------------------------
  def avatar
    respond_with(@user)
  end

  # PUT /users/1/upload_avatar
  # PUT /users/1/upload_avatar.js
  #----------------------------------------------------------------------------
  def upload_avatar
    if params[:gravatar]
      @user.avatar = nil
      @user.save
      render
    else
      if params[:avatar]
        avatar = Avatar.create(avatar_params)
        if avatar.valid?
          @user.avatar = avatar
        else
          @user.avatar.errors.clear
          @user.avatar.errors.add(:image, t(:msg_bad_image_file))
        end
      end
      responds_to_parent do
        # Without return RSpec2 screams bloody murder about rendering twice:
        # within the block and after yield in responds_to_parent.
        render && (return if Rails.env.test?)
      end
    end
  end

  # GET /users/1/password
  # GET /users/1/password.js
  #----------------------------------------------------------------------------
  def password
    respond_with(@user)
  end

  # PUT /users/1/change_password
  # PUT /users/1/change_password.js
  #----------------------------------------------------------------------------
  def change_password
    if @user.valid_password?(params[:current_password], true) || @user.password_hash.blank?
      unless params[:user][:password].blank?
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        @user.save
        flash[:notice] = t(:msg_password_changed)
      else
        flash[:notice] = t(:msg_password_not_changed)
      end
    else
      @user.errors.add(:current_password, t(:msg_invalid_password))
    end

    respond_with(@user)
  end

  # GET /users/1/redraw
  #----------------------------------------------------------------------------
  def redraw
    current_user.preference[:locale] = params[:locale]
    render js: %(window.location.href = "#{user_path(current_user)}";)
  end

  # GET /users/opportunities_overview
  #----------------------------------------------------------------------------
  def opportunities_overview
    @users_with_opportunities = User.have_assigned_opportunities.order(:first_name)
    @unassigned_opportunities = Opportunity.my.unassigned.pipeline.order(:stage)
  end

  protected

  def user_params
    params[:user].permit(
      :username,
      :email,
      :first_name,
      :last_name,
      :title,
      :company,
      :alt_email,
      :phone,
      :mobile,
      :aim,
      :yahoo,
      :google,
      :skype
    )
  end

  def avatar_params
    params[:avatar]
      .permit(:image)
      .merge(entity: @user)
  end
end

app/helpers/admin/users_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module Admin::UsersHelper
  def link_to_suspend(user)
    link_to(t(:suspend) + "!", suspend_admin_user_path(user), method: :put, remote: true)
  end

  #----------------------------------------------------------------------------
  def link_to_reactivate(user)
    name = user.awaits_approval? ? t(:approve) + "!" : t(:reactivate) + "!"
    link_to(name, reactivate_admin_user_path(user), method: :put, remote: true)
  end

  #----------------------------------------------------------------------------
  def link_to_confirm(user)
    link_to(t(:delete) + "?", confirm_admin_user_path(user), method: :get, remote: true)
  end

  # User summary info for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def user_summary(user)
    summary = []
    title_and_company = user.title.blank? ? '' : h(user.title)
    title_and_company << " #{t(:at)} #{user.company}" unless user.company.blank?
    summary << title_and_company unless title_and_company.blank?
    summary << t('pluralize.login', user.login_count) if user.current_login_at && user.login_count > 0
    summary << user.email
    summary << "#{t :phone_small}: #{user.phone}" unless user.phone.blank?
    summary << "#{t :mobile_small}: #{user.mobile}" unless user.mobile.blank?
    summary << if !user.suspended?
                 t(:user_since, l(user.created_at.to_date, format: :mmddyy))
               elsif user.awaits_approval?
                 t(:user_signed_up_on, l(user.created_at, format: :mmddhhss))
               else
                 t(:user_suspended_on, l(user.created_at.to_date, format: :mmddyy))
    end
    summary << if user.awaits_approval?
                 t(:user_signed_up)
               elsif user.suspended?
                 t(:user_suspended)
               elsif user.admin?
                 t(:user_admin)
               else
                 t(:user_active)
    end
    summary.join(', ')
  end
end

app/helpers/users_helper.rb
# Copyright (c) 2008-2013 Michael Dvorkin and contributors.
#
# Fat Free CRM is freely distributable under the terms of MIT license.
# See MIT-LICENSE file or http://www.opensource.org/licenses/mit-license.php
#------------------------------------------------------------------------------
module UsersHelper
  def language_for(user)
    if user.preference[:locale]
      locale, language = languages.detect { |locale, _language| locale == user.preference[:locale] }
    end
    language || "English"
  end

  def sort_by_language
    languages.sort.map do |locale, language|
      %[{ name: "#{language}", on_select: function() { #{redraw(:locale, [locale, language], url_for(action: :redraw, id: current_user))} } }]
    end
  end

  def all_users
    User.by_name
  end

  def user_select(asset, users, myself)
    user_options = user_options_for_select(users, myself)
    select(asset, :assigned_to, user_options,
           { include_blank: t(:unassigned) },
           style:         "width:160px",
           class: 'select2')
  end

  def user_options_for_select(users, myself)
    (users - [myself]).map { |u| [u.full_name, u.id] }.prepend([t(:myself), myself.id])
  end
end

app/views/users/backup_originals/_avatar.html.haml
.remote
  = form_for(@user, :url => upload_avatar_user_path(@user, :format => "js"), :html => { :multipart => true, :target => "uploading", :onsubmit => "$('#user_avatar_submit').disabled = true" }) do |f|
    = link_to_close avatar_user_path(@user)
    = error_messages_for :avatar, :object => @user.avatar, :object_name => t('avatar')

    %p
      %small #{t :image_help}

    %div #{t :image_file}:
    = fields_for(Avatar) do |a|
      %div= a.file_field :image

    .buttonbar
      %small.cool{:style => "float:right"}== #{t :gravatar_help} #{link_to(t(:here), "http://en.gravatar.com", :"data-popup" => true)}.
      = f.submit t(:upload_picture), :id => "user_avatar_submit"
      #{t :or}
      = link_to(t(:use_gravatar), upload_avatar_user_path(@user) + '?gravatar=1', :method => :put, :remote => true)
      #{t :or}
      = link_to_cancel avatar_user_path(@user)
%br

app/views/users/backup_originals/_languages.html.haml
:plain
  new crm.Menu({
    trigger   : "#locale",
    align     : "right",
    appear    : 500,
    fade      : 500,
    width     : 160,
    menu_items: [ #{sort_by_language.join(",")} ]
  });

app/views/users/backup_originals/_password.html.haml
.remote
  = form_for(@user, :url => change_password_user_path(@user), :html => one_submit_only, :remote => true) do |f|
    = link_to_close password_user_path(@user)

    = f.error_messages :object_name => t('password')

    .section
      %table
        %tr
          %td
            .label.req.top #{t :current_password}:
            = password_field_tag :current_password, nil
          %td{ :colspan => 2 }= spacer
        %tr
          %td
            .label.req #{t :new_password}:
            = f.password_field :password
          %td= spacer
          %td
            .label.req #{t :password_confirmation}:
            = f.password_field :password_confirmation

    .buttonbar
      = f.submit t(:change_password)
      #{t :or}
      = link_to_cancel password_user_path(@user)
%br

app/views/users/backup_originals/_profile.html.haml
.remote
  = form_for(@user, :html => one_submit_only, :remote => true) do |f|
    = link_to_close edit_user_path(@user)

    = f.error_messages :object_name => t('user')

    .section
      %table
        %tr
          %td
            .label.top #{t :first_name}:
            = f.text_field :first_name
          %td= spacer
          %td
            .label.top #{t :last_name}:
            = f.text_field :last_name
        %tr
          %td
            .label.top #{t :job_title}:
            = f.text_field :title
          %td= spacer
          %td
            .label.top #{t :company}:
            = f.text_field :company
    .subtitle #{t :contact_info}
    .section
      %table
        %tr
          %td{ :colspan => 3 }
            .label.top.req #{t :email}:
            = f.text_field :email
          %td= spacer
          %td{ :colspan => 3 }
            .label.top #{t :alt_email}:
            = f.text_field :alt_email
        %tr
          %td{ :colspan => 3 }
            .label #{t :phone}:
            = f.text_field :phone
          %td= spacer
          %td{ :colspan => 3 }
            .label #{t :mobile}:
            = f.text_field :mobile
        %tr
          %td
            .label #{t :aim}:
            = f.text_field :aim, :style => "width:112px"
          %td= spacer
          %td
            .label #{t :yahoo}:
            = f.text_field :yahoo, :style => "width:112px"
          %td= spacer
          %td
            .label #{t :google}:
            = f.text_field :google, :style => "width:112px"
          %td= spacer
          %td
            .label #{t :skype}:
            = f.text_field :skype, :style => "width:112px"

    .buttonbar
      = f.submit t :save_profile
      #{t :or}
      = link_to_cancel edit_user_path(@user)

  = hook(:profile_user_bottom, self)
%br

app/views/users/backup_originals/_user.html.haml
- if @user == current_user && Setting.per_user_locale
  %div#options(style="float:right")
    #{t :profile_language}: #{link_to(language_for(current_user), "#", :id => :locale)}

%table(cellspacing="0" cellpadding="0")
  %tr
    %td(valign="top")
      = avatar_for(@user, :style => "margin: 0px 10px 0px 0px")
    %td(valign="top")
      %h3= h(@user.full_name) + " (#{@user.username})"
      - if !@user.title.blank? && !@user.company.blank?
        %div= t(:works_at, :job_title => h(@user.title), :company => h(@user.company))
      - else
        = h(@user.title) unless @user.title.blank?
        = h(@user.company) unless @user.company.blank?
      %br
      %div
        #{t :email}: #{auto_link(@user.email)}
        - unless @user.alt_email.blank?
          #{t :or} #{auto_link(@user.alt_email)}
      - if !@user.phone.blank? && !@user.mobile.blank?
        %div #{t :phone}: <b>#{@user.phone}</b>, #{t :mobile}: <b>#{@user.mobile}</b>
      - else
        - if @user.phone.present?
          = t(:phone) + ":"
          = content_tag(:b, @user.phone)
        - if @user.mobile.present?
          = t(:mobile) + ":"
          = content_tag(:b, @user.mobile)

- if Setting.per_user_locale
  %script= render "languages"

app/views/users/backup_originals/_user_report.html.haml
%li{:id => dom_id(user_report)}
  .title
    %span#title
      = user_report.full_name
  %ul.list#opportunities
    = render :partial => "opportunities/opportunity", :collection => user_report.assigned_opportunities.pipeline.order("opportunities.amount DESC")

app/views/users/backup_originals/change_password.js.haml
- if @user.errors.empty?
  crm.flip_form('change_password');
  crm.set_title('change_password', '#{ j t(:my_profile) }');
  $('#flash').html('#{ j flash[:notice] }');
  crm.flash('notice')
  - flash[:notice] = nil
- else
  $('#change_password').html('#{ j render(:partial => "password") }');
  $('#change_password').effect("shake", { duration:250, distance: 6 });
  - if @user.errors[:current_password].present?
    $('#current_password').focus();
  - else
    $('#user_password').focus();

app/views/users/backup_originals/edit.js.haml
- if params[:cancel].true?
  crm.flip_form('edit_profile');
  crm.set_title('edit_profile', '#{ j t(:my_profile) }');
- else
  $('#edit_profile').html('#{ j render(:partial => "profile") }');
  crm.hide_form('upload_avatar');
  crm.hide_form('change_password');
  crm.flip_form('edit_profile');
  crm.set_title('edit_profile', '#{t(:edit_profile)}');

app/views/users/backup_originals/index.html.haml
.title_tools
  .title #{t :user}
%p #{t :not_implemented}

app/views/users/backup_originals/new.html.haml
.standalone
  = form_for(@user, :html => one_submit_only) do |f|
    .title_tools #{t :already_signed_up} #{link_to t(:login_now_link), login_path}
    .title #{t :sign_up}

    = f.error_messages :object_name => t('user')

    .section
      .label #{t :email}:
      = f.text_field :email
      .label #{t :username}:
      = f.text_field :username
      .label #{t :password}:
      = f.password_field :password
      .label #{t :password_confirmation}:
      = f.password_field :password_confirmation

    .buttonbar
      = f.submit t(:sign_up_button)

app/views/users/backup_originals/opportunities_overview.html.haml
= styles_for :opportunity

#create_opportunity{ hidden }

- if @users_with_opportunities.any? || @unassigned_opportunities.any?
  %ul
    = render :partial => "user_report", :collection => @users_with_opportunities
    - if @unassigned_opportunities.any?
      #unassigned
        .title
          %span#title
            = t(:unassigned_opportunities)
        %ul.list#opportunities
          = render :partial => "opportunities/opportunity", :collection => @unassigned_opportunities
- else
  = t(:no_opportunities_found)

app/views/users/backup_originals/password.js.haml
- if params[:cancel].true?
  crm.flip_form('change_password');
  crm.set_title('change_password', '#{t(:my_profile)}');
- else
  $('#change_password').html('#{ j render(:partial => "password") }');
  crm.hide_form('edit_profile');
  crm.hide_form('upload_avatar');
  crm.flip_form('change_password');
  crm.set_title('change_password', '#{t(:change_password)}');
  $('#current_password').focus();

app/views/users/backup_originals/update.js.haml
- if @user.errors.empty?
  crm.flip_form('edit_profile');
  crm.set_title('edit_profile', '#{j t(:my_profile)}');
  $('#welcome_username').html('#{j current_user.name}');
  $('#profile').html('#{ j render(:partial => "user") }');
- else
  $('#edit_profile').html('#{ j render(:partial => "profile") }');
  $('#edit_profile').effect("shake", { duration:250, distance: 6 });
  $('#user_email').focus();

app/views/users/backup_originals/upload_avatar.js.haml
- if @user.avatar.nil? || @user.avatar.errors.empty?
  crm.flip_form('upload_avatar');
  crm.set_title('upload_avatar', '#{j t(:my_profile)}');
  $('#profile').html('#{ j render(:partial => "user") }');
- else
  $('#upload_avatar').html('#{ j render(:partial => "avatar") }');
  $('#upload_avatar').effect("shake", { duration:250, distance: 6 });